version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  share-my-repo:
    container_name: share-my-repo
    networks:
      - proxy-net
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=share-my-repo.vibr.app
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=share-my-repo.vibr.app
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
