version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  social-gh:
    container_name: social-gh
    networks:
      - proxy-net
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=social-gh.viktor-braun.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=social-gh.viktor-braun.de
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
